class AIOKafkaProducer:
    def __init__(self, *, bootstrap_servers: str) -> None: ...
    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def send_and_wait(
        self,
        topic: str,
        value: bytes | None = ...,
        key: bytes | None = ...,
    ) -> object: ...
