config:
  clients:
    - url: http://loki.obs.svc.cluster.local:3100/loki/api/v1/push
  snippets:
    pipelineStages:
      - cri: {}

resources:
  requests:
    cpu: 20m
    memory: 48Mi
  limits:
    cpu: 200m
    memory: 128Mi
